src/Entity/Reclamation.php
<?php

namespace App\Entity;

use App\Repository\ReclamationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ReclamationRepository::class)]
class Reclamation
{

    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: "AUTO")]
    #[ORM\Column(type: Types::BIGINT)]
    private ?string $NumReclamation = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank(message: 'The reclamation should not be blank')]
    private ?string $CorpReclamation = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $DateReclamation = null;

    #[ORM\ManyToOne(inversedBy: 'reclamations')]
    #[ORM\JoinColumn(nullable: false, name: 'utilisateur_id', referencedColumnName: 'pseudo_nom')]
    private ?Utilisateur $utilisateur = null;

    public function getNumReclamation(): ?string
    {
        return $this->NumReclamation;
    }

    public function setNumReclamation(string $NumReclamation): static
    {
        $this->NumReclamation = $NumReclamation;

        return $this;
    }

    public function getCorpReclamation(): ?string
    {
        return $this->CorpReclamation;
    }

    public function setCorpReclamation(string $CorpReclamation): static
    {
        $this->CorpReclamation = $CorpReclamation;

        return $this;
    }

    public function getDateReclamation(): ?\DateTimeInterface
    {
        return $this->DateReclamation;
    }

    public function setDateReclamation(\DateTimeInterface $DateReclamation): static
    {
        $this->DateReclamation = $DateReclamation;

        return $this;
    }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->utilisateur;
    }

    public function isBelongsTo(Utilisateur $utilisateur): bool
    {
        return $this->getUtilisateur()->getUserIdentifier() == $utilisateur->getUserIdentifier();
    }

    public function setUtilisateur(?Utilisateur $utilisateur): static
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }
}

src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use App\Repository\UtilisateurRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: UtilisateurRepository::class)]
#[UniqueEntity(fields: ['PseudoNom'], message: 'There is already an account with this PseudoNom')]
class Utilisateur implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\Column(length: 50)]
    #[Assert\NotBlank(message: 'pseudo nom should not be blank')]
    private ?string $PseudoNom = null;

    #[ORM\Column(length: 50, nullable: true)]
    #[Assert\NotBlank(message: 'nom should not be blank')]
    private ?string $nom = null;

    #[ORM\Column(length: 50, nullable: true)]
    #[Assert\NotBlank(message: 'prenom should not be blank')]
    private ?string $prenom = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(message: 'addresse should not be blank')]
    private ?string $adresse = null;

    #[ORM\Column(length: 2)]
    #[Assert\NotBlank(message: 'sexe should not be blank')]
    private ?string $sexe = null;

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    // #[Assert\NotBlank(message: 'password should not be blank')]
    private ?string $password = null;

    #[ORM\Column(length: 40, nullable: true)]
    #[Assert\NotBlank(message: 'profession should not be blank')]
    private ?string $profession = null;

    #[ORM\Column]
    private array $roles = [];

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    #[Assert\NotBlank(message: 'This value should not be blank')]
    private ?\DateTimeInterface $dateNaissance = null;

    #[ORM\OneToMany(mappedBy: 'utilisateur', targetEntity: Reclamation::class, orphanRemoval: true)]
    private Collection $reclamations;

    public function __construct()
    {
        $this->reclamations = new ArrayCollection();
        $this->sexe = "M";
    }


    public function getPseudoNom(): ?string
    {
        return $this->PseudoNom;
    }

    public function setPseudoNom(string $PseudoNom): static
    {
        $this->PseudoNom = $PseudoNom;

        return $this;
    }


    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): static
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getProfession(): ?string
    {
        return $this->profession;
    }

    public function setProfession(?string $profession): static
    {
        $this->profession = $profession;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->dateNaissance;
    }

    public function setDateNaissance(?\DateTimeInterface $dateNaissance): static
    {
        $this->dateNaissance = $dateNaissance;

        return $this;
    }
    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->PseudoNom;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function isAdmin(): bool
    {
        return in_array("ROLE_ADMIN",$this->getRoles());
    }
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @return Collection<int, Reclamation>
     */
    public function getReclamations(): Collection
    {
        return $this->reclamations;
    }

    public function addReclamation(Reclamation $reclamation): static
    {
        if (!$this->reclamations->contains($reclamation)) {
            $this->reclamations->add($reclamation);
            $reclamation->setUtilisateur($this);
        }

        return $this;
    }

    public function removeReclamation(Reclamation $reclamation): static
    {
        if ($this->reclamations->removeElement($reclamation)) {
            // set the owning side to null (unless already changed)
            if ($reclamation->getUtilisateur() === $this) {
                $reclamation->setUtilisateur(null);
            }
        }

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

src/Controller/ReclamationController.php
<?php

namespace App\Controller;

use App\Entity\Reclamation;
use App\Entity\Utilisateur;
use App\Form\ReclamationFormType;
use App\Repository\ReclamationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;

class ReclamationController extends AbstractController
{
    private $entityManager;
    private $reclamationRepository;
    public function __construct(EntityManagerInterface $entityManager, ReclamationRepository $reclamationRepository)
    {
        $this->entityManager = $entityManager;
        $this->reclamationRepository = $reclamationRepository;
    }



    #[Route('/reclamation', name: 'app_reclamation')]
    public function index(Request $request): Response
    {
        $reclamation = new Reclamation();
        $form = $this->createForm(ReclamationFormType::class, $reclamation);

        // show the reclamation o the current user
        $utilisateur = $this->entityManager->getRepository(Utilisateur::class)->find($this->getUser()->getUserIdentifier());

        $reclamations = $utilisateur->getReclamations();

        try {
            $form->handleRequest($request);
            if ($form->isSubmitted() && $form->isValid()) {
                
                $reclamation->setDateReclamation(new \DateTime());

                $reclamation->setUtilisateur($utilisateur);

                $this->entityManager->persist($reclamation);
                $this->entityManager->flush();
                
                // 
                $this->addFlash('message', 'reclamation added successfully');

                return $this->redirectToRoute('app_reclamation');
            }
        } catch (\Exception $e) {
            dd($e->getMessage());
        }


        return $this->render('reclamation/index.html.twig', [
            'form' => $form->createView(),
            'reclamations' => $reclamations,
        ]);
    }

    #[Route('/reclamation/{id}', name: 'visit_reclamation')]
    public function view($id): Response
    {
        $reclamation = $this->reclamationRepository->find($id);

        if ($reclamation && ($reclamation->isBelongsTo($this->getUser()) || $this->getUser()->isAdmin())) {
            $utilisateur = $reclamation->getUtilisateur();
            return $this->render('reclamation/view.html.twig', [
                "reclamation" => $reclamation,
                "utilisateur" => $utilisateur,

            ]);
        } else {
            return $this->redirectToRoute('404');
        }


    }

    #[Route('/reclamation/{id}/edit', name: 'edit_reclamation')]
    public function edit(Request $request, $id): Response
    {
        $reclamation = $this->reclamationRepository->find($id);
        


        if ($reclamation && ($reclamation->isBelongsTo($this->getUser()) || $this->getUser()->isAdmin())) {
            $utilisateur = $reclamation->getUtilisateur();

            $form = $this->createForm(ReclamationFormType::class, $reclamation);

            try {
                $form->handleRequest($request);

                if ($form->isSubmitted() && $form->isValid()) {

                    $reclamation->setCorpReclamation($form->get('CorpReclamation')->getData());
                    $this->entityManager->flush();

                $this->addFlash('message', 'reclamation updated successfully');


                    return $this->redirectToRoute('edit_reclamation', ['id' => $id]);
                }
            } catch (\Exception $e) {
                return $this->redirectToRoute('edit_reclamation' , ['id' => $id]);
            }

            return $this->render('reclamation/edit.html.twig', [
                'form' => $form->createView(),
                'utilisateur' => $utilisateur,
                'reclamation' => $reclamation,
            ]);
        } else {
            return $this->redirectToRoute('404');
        }

    }

    #[Route("/reclamation/{id}/delete", name: "delete_reclamation", methods: ['POST'])]
    public function delete($id): Response
    {
        $reclamation = $this->reclamationRepository->find($id);
        if ($reclamation && ($reclamation->isBelongsTo($this->getUser()) || $this->getUser()->isAdmin())) {
            $this->entityManager->remove($reclamation);
            $this->entityManager->flush();

            if ($this->getUser()->isAdmin()) {
                return $this->redirectToRoute('app_dashboard');
            } else {
                return $this->redirectToRoute('app_reclamation');
            }
        }
        return $this->redirectToRoute('app_reclamation');

    }
}

templates/reclamation/edit.html.twig
{% extends 'base.html.twig' %}
{% block styles %}
	<style>
		body::after {
			content: none !important;
		}
	</style>
{% endblock %}
{% block title %}editer Reclamation
{% endblock %}

{% block body %}
{% for message in app.flashes('message') %}
	<div class="alert alert-info col-12 col-md-6 col-lg-6 text-center shadow position-fixed start-50 translate-middle-x" style="top:70px" role="alert">
		<strong>{{message}}</strong>
	</div>
{% endfor %}
	<div class="container">
		<div class="d-flex align-items-center ">
			{% if utilisateur.sexe == "F" %}
				<img src="{{asset('/build/images/female.b230c6621b93f3f9a6e53e4b1be898f7.jpg')}}" class="rounded-circle" alt="avatar" width="100" height="100">
			{% else %}
				<img src="{{asset('/build/images/male.c1491bb6860c1d32f6304ce3f1958c05.jpg')}}" class="rounded-circle" alt="avatar" width="100" height="100">
			{% endif %}
			<div class="d-flex flex-column mx-3">
				<h3 class="fw-bold my-0">{{utilisateur.nom|upper}}
					{{utilisateur.prenom}}</h3>
				<h3>@{{utilisateur.pseudoNom}}</h3>
			</div>

		</div>
		<hr>
		<div class="p-2">
			<p class="text-muted">{{reclamation.dateReclamation | date("Y-m-d")}}</p>
			<div class="col-md-8 col-lg-6 col-sm-10">
				{{ form_start(form) }}

				{{ form_widget(form) }}

				<button class="btn px-5 mt-3 py-2 btn-primary rounded-5 shadow">Editer</button>
				{{ form_end(form) }}
			</div>
		</div>
	</div>
		{% block scripts %}
			<script>
				setTimeout(() => {
$(".alert").remove();
}, 7000);
			</script>
		{% endblock %}
{% endblock %}

templates/reclamation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter Reclamation
{% endblock %}

{% block body %}

	{% for message in app.flashes('message') %}
		<div class="alert alert-info col-12 col-md-6 col-lg-6 shadow text-center position-fixed start-50 translate-middle-x" style="top:70px" role="alert">
			<strong>{{message}}</strong>
		</div>
	{% endfor %}

	<div class="d-flex flex-column  align-items-center text-center" style="margin-top:-20px">
		<img src="{{asset('build/images/paper.c5174ddb009019ff379da96012613ad2.png')}}" alt="cible" width="170px" height="170px">
		<h1 class="fw-bold">Ajouter Une Reclamation</h1>
		<p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex, labore.</p>
		<div class="col-md-8 col-lg-6 col-sm-10">
			{{ form_start(form) }}

			{{ form_widget(form) }}

			<button class="btn px-5 col-12 mt-3 py-2 btn-primary rounded-5 shadow">Ajouter</button>
			{{ form_end(form) }}

		</div>

		<div class="flex px-2 align-items-center justify-content-center text-center my-4">
			<h1 class="fw-bold mt-5">Votre Reclamations</h1>
			<p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur, molestias.</p>
		</div>

		<table class="table table-hover mt-4">
			<thead>
				<tr>
					<th scope="col">#</th>
					<th scope="col">Reclamations</th>
					<th scope="col">Date</th>
					<th scope="col">Action</th>
				</tr>
			</thead>
			<tbody>
				{% for reclamation in reclamations %}
					<tr>
						<th scope="row">{{loop.index}}</th>
						<td>
							{% if reclamation.corpReclamation|length > 20 %}
								{{ reclamation.corpReclamation|slice(0, 20) ~ '...' }}
							{% else %}
								{{ reclamation.corpReclamation }}
							{% endif %}
						</td>
						<td>{{reclamation.dateReclamation | date("Y-m-d") }}</td>
						<td>
							<div class="btn-group">
								<button class="bg-transparent" type="button" id="triggerId" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									<i class="fa fa-ellipsis-v" aria-hidden="true"></i>
								</button>
								<div class="dropdown-menu dropdown-menu-right" aria-labelledby="triggerId">
									<a class="dropdown-item" href="/reclamation/{{reclamation.NumReclamation}}">
										<i class="fa fa-eye" aria-hidden="true"></i>
										visit
									</a>
									<a class="dropdown-item" href="{{path('edit_reclamation', {'id': reclamation.NumReclamation})}}">
										<i class="fa fa-pencil" aria-hidden="true"></i>
										editer
									</a>
									<form action="{{path('delete_reclamation', {'id': reclamation.NumReclamation})}}" method="POST">
										<button class="dropdown-item bg-transparent" onclick="confirmer()">
											<i class="fas fa-trash-alt"></i>
											supprimer
										</button>
									</form>
								</div>
							</div>
						</td>
					</tr>
				{% else %}
					<tr class="bg-white">
						<td colspan="8" class="bg-white">
							<div class="d-flex col-12 p-4 justify-content-center align-items-center">
								<img src="{{asset('build/images/no_data.bfb5d09f027311a51c0c2adbe2dad775.png')}}" alt="cible" width="300px" height="300px">
							</div>
						</td>
					</tr>

				{% endfor %}

			</tbody>
		</table>
		{% block scripts %}
			<script>
				setTimeout(() => {
$(".alert").remove();
}, 7000);
			</script>
		{% endblock %}

	{% endblock %}

templates/reclamation/view.html.twig
{% extends 'base.html.twig' %}
{% block styles %}
	<style>
		body::after {
			content: none !important;
		}
	</style>
{% endblock %}
{% block title %}View Reclamation
{% endblock %}

{% block body %}
	<div class="container">
		<div class="d-flex align-items-center ">
			{% if utilisateur.sexe == "F" %}
				<img src="{{asset('/build/images/female.b230c6621b93f3f9a6e53e4b1be898f7.jpg')}}" class="rounded-circle" alt="avatar" width="100" height="100">
			{% else %}
				<img src="{{asset('/build/images/male.c1491bb6860c1d32f6304ce3f1958c05.jpg')}}" class="rounded-circle" alt="avatar" width="100" height="100">
			{% endif %}
			<div class="d-flex flex-column mx-3">
				<h3 class="fw-bold my-0">{{utilisateur.nom|upper}}
					{{utilisateur.prenom}}</h3>
				<h3>@{{utilisateur.pseudoNom}}</h3>
			</div>

		</div>
		<hr>
		<div class="p-2">
			<p class="text-muted">{{reclamation.dateReclamation | date("Y-m-d")}}</p>
			<p>{{reclamation.corpReclamation}}</p>
		</div>
	</div>
{% endblock %}